### ISSUE TITLE
handle '#include MACRO'

### ISSUE THREAD

**Issue by danmar** [danmar/simplecpp#3]
Original ticket: http://trac.cppcheck.net/ticket/3654

**Comment by danmar** [comment]
Other ticket: http://trac.cppcheck.net/ticket/4571

**Comment by mavik1** [comment]
This issue is present in cppcheck 1.76.1. It is possible to reopen this ticket?

**Comment by danmar** [comment]
How is this different to #34?

**Comment by mavik1** [comment]
The test cases are on http://trac.cppcheck.net/ticket/3654 and http://trac.cppcheck.net/ticket/4571. Ticket #34 was classified as a duplicate of this ticket, so they may be equivalent although the test cases are not identical.

**Comment by danmar** [comment]
I don't see a testcase in http://trac.cppcheck.net/ticket/3654

The testcase in  http://trac.cppcheck.net/ticket/4571 is quite obfuscated. There is a:

    #include __FILE__

in the middle. I assume that is what is not handled well. it should be possible to simplify the testcase.

**Comment by fnxweb** [comment]
Not really sure where to put this, so for now I'll comment on this issue instead of raising a new one or commenting on issue #34.

This issue was borne of http://trac.cppcheck.net/ticket/3654, which itself caused http://trac.cppcheck.net/ticket/4424 to be closed as a dup.  It is this latter issue that we raised some time ago but seems to have become lost in the myriad jumps between flavours of the problem, and has itself never been fixed.

Unfortunately, it has been exacerbated by cppcheck 1.77+ which is now flagging these situations as errors.  Here's the most simple example;  I will admit that in being simpler to the original reported issue 4424 it may actually be a separate issue (albeit in the same area):

```
#define INCLUDE_LOCATION ../somewhere
#define INCLUDE_FILE(F)  <INCLUDE_LOCATION/F.h>

// Error line
#include INCLUDE_FILE(header)

int main()
{
    return 0;
}


$ cppcheck-1.79 macroinclude.cpp
Checking macroinclude.cpp ...
[macroinclude.cpp:5]: (error) No header in #include
```

I'm happy to raise this example as a new issue if you want, but from my perspective this is the same bug that has spanned all these issues and that I've not actually seen solved.


Sorry, re-reading that it comes across as a bit more moany than I was intending!  I'm just a bit confused as to where I should be commenting on this now.

**Comment by fnxweb** [comment]
Further:  the original issue also still does not work, but in this case quietly — no error, it just doesn't do the include.

```
// Second example
#define _1ASSTRING(token)  #token
#define AS_STRING(token)  _1ASSTRING(token)
#include AS_STRING(types.h)
```

When I double checked with _strace_, I got a slightly amusing output which gives me a hint as to what's going wrong (if not where)!

```
Checking macroinclude.cpp ...
open("NCLUDE_FIL", O_RDONLY|O_LARGEFILE) = -1 ENOENT (No such file or directory)
open("S_STRIN", O_RDONLY|O_LARGEFILE)   = -1 ENOENT (No such file or directory)
```

Although presumably the mistake it's making wouldn't occur if the macro expansion had happened.

**Comment by danmar** [comment]
@fnxweb thanks. I am looking at this now. I like to have small tickets so I can close them with small simple fixes. I would appreciate a separate ticket for each unhandled use case you see. sorry for such a late reply.

**Comment by fnxweb** [comment]
Sorry, did you want me to create a new ticket then?

**Comment by danmar** [comment]
I would appreciate if you create new separate tickets for the issues you see.

**Comment by fnxweb** [comment]
No probs., raised issue #119
