### ISSUE TITLE
cppcheck warnings

### ISSUE THREAD

**Issue by necros2k7** [danmar/simplecpp#52]
[externals\simplecpp\simplecpp.cpp:1841] -> [externals\simplecpp\simplecpp.cpp:1844]: (style, inconclusive) Variable 'ret[header2]' is reassigned a value before the old one has been used if variable is no semaphore variable.
[externals\simplecpp\simplecpp.cpp:189]: (warning, inconclusive) Member variable 'TokenList::files' is not assigned a value in 'TokenList::operator='.
[externals\simplecpp\simplecpp.cpp:920]: (warning, inconclusive) Member variable 'Macro::files' is not assigned a value in 'Macro::operator='.
[externals\simplecpp\simplecpp.cpp:920]: (warning, inconclusive) Member variable 'Macro::usageList' is not assigned a value in 'Macro::operator='.
[externals\simplecpp\simplecpp.cpp:920]: (style) 'Macro::operator=' should return 'Macro &'.
[externals\simplecpp\simplecpp.cpp:1530]: (performance, inconclusive) Technically the member function 'simplecpp::Macro::isReplaced' can be static.
[externals\simplecpp\simplecpp.cpp:0]: (information) The configuration 'SIMPLECPP_IMPORT;_WIN32' was not checked because its code equals another one.
[externals\simplecpp\simplecpp.cpp:0]: (information) The configuration '_WIN32' was not checked because its code equals another one.
[externals\simplecpp\simplecpp.cpp:0]: (information) The configuration '_WIN32;__CYGWIN__;**MINGW32**' was not checked because its code equals another one.

**Comment by amai2012** [comment]
Did you validate the results? Despite the facts that information shouldn't raise any concern anyway...

**Comment by danmar** [comment]
Yes always validate Cppcheck results before you submit. There is 1 good finding that I do care about and fixed:

    Variable 'ret[header2]' is reassigned a value

The files are not assigned by intention because the data is always identical.

The usageList is not assigned.. I am not sure if it should.

I don't care about that operator=. I return void by intention.

It feels wrong to make isReplaced static even if it is technically possible.

**Comment by necros2k7** [comment]
How to validate?

**Comment by danmar** [comment]
it is ok. but please don't report unvalidated reports to other projects.

If you report 1 error message that turns out to be a real bug then people will probably be grateful.

If you report 100 messages and most are not important then people can get bad feelings. Both against you and Cppcheck.

If you are not a programmer then it will be hard to know if a Cppcheck-message is important or not. Sometimes Cppcheck is wrong, so even though Cppcheck says it's important you should not trust it.

**Comment by necros2k7** [comment]
ok
